### ISSUE TITLE
Response not being sent back as json

### ISSUE THREAD

**Issue by bryandease** [Vinelab/api-manager#2]
I'm having a different result from the documentation as far as the response type.  If I use Api::respond or Api::error I'm getting a header type of text/html.  If I use Api::content it's coming back as application/json.  How would I get a correct header sent using the error or respond method?

**Comment by Mulkave** [comment]
@bryandease What you're suggesting is to take the request's `Accept` header into consideration and return the `Content-Type` accordingly with the response ?

**Comment by bryandease** [comment]
Yes - that's pretty much what my refactor does - just defaulting to json if no headers are sent.

**Comment by Mulkave** [comment]
@bryandease this has been added in https://github.com/Vinelab/api-manager/blob/master/src/Vinelab/Api/Responder.php#L35

Thanks for the feedback.
